///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace rx_git_proj1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the rx_git_proj1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("23185671-d1e3-4e71-98bc-6bb2dbe88747")]
    public partial class rx_git_proj1Repository : RepoGenBaseFolder
    {
        static rx_git_proj1Repository instance = new rx_git_proj1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the rx_git_proj1Repository element repository.
        /// </summary>
        [RepositoryFolder("23185671-d1e3-4e71-98bc-6bb2dbe88747")]
        public static rx_git_proj1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public rx_git_proj1Repository() 
            : base("rx_git_proj1Repository", "/", null, 0, false, "23185671-d1e3-4e71-98bc-6bb2dbe88747", ".\\RepositoryImages\\rx_git_proj1Repository23185671.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("23185671-d1e3-4e71-98bc-6bb2dbe88747")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class rx_git_proj1RepositoryFolders
    {
    }
#pragma warning restore 0436
}
